spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
            - name: Retry
              args:
                methods: GET,POST,PUT,DELETE
            - RewritePath=/api/orders(?<remaining>.*), /${remaining}

# Enabling Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false

ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true