spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
      routes:
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
            - name: Retry
              args:
                methods: GET,POST,PUT,DELETE
            - RewritePath=/api(?<remaining>.*), /${remaining}
        - id: client-service-route
          uri: lb://client-service
          predicates:
            - Path=/api/v1/clients/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
            - name: Retry
              args:
                methods: GET,POST,PUT,DELETE
            - RewritePath=/api(?<remaining>.*), /${remaining}

# Enabling Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true