server:
  port: 8081

spring:
  application:
    name: client-service
  data:
    rest:
      basePath: /v1
    mongodb:
      uri: mongodb://localhost/clients

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}