server:
  port: ${SERVICE_PORT:8081}

spring:
  application:
    name: client-service
  data:
    rest:
      basePath: /v1

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG