server:
  port: ${SERVICE_PORT:8082}

spring:
  application:
    name: order-service
  data:
    rest:
      basePath: /v1
    mongodb:
      uri: mongodb://localhost/orders

eureka:
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    enabled: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}