server:
  port: ${SERVICE_PORT:8082}

spring:
  application:
    name: order-service
  data:
    rest:
      basePath: /v1
  cache:
    type: redis
    redis:
      time-to-live: 30000
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

feign:
  hystrix:
    enabled: true

logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: DEBUG
        data:
          mongodb: DEBUG