server:
  port: ${SERVICE_PORT:8082}

spring:
  application:
    name: order-service
  data:
    rest:
      basePath: /v1
    mongodb:
      uri: mongodb://localhost/orders

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

feign:
  hystrix:
    enabled: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG